# Generated by Django 6.0.3 on 2026-04-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_update_medication_for_prescriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='refill_reminder_date',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='refill_reminder_days_before',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='refill_reminder_enabled',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='reminder_days',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='reminder_enabled',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='reminder_time',
        ),
        migrations.AlterField(
            model_name='medication',
            name='administration_instructions',
            field=models.TextField(blank=True),
        ),
    ]
