# Generated by Django 6.0.3 on 2026-04-07 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_healthcare_provider'),
        ('authentication', '0002_patient_family_members'),
    ]

    operations = [
    ]
