# Generated by Django 6.0.3 on 2026-04-08 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20260407_1538'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovider',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('family_member', 'Family Member'), ('healthcare_provider', 'Healthcare Provider')], max_length=20),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_to_patient', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('aunt_uncle', 'Aunt/Uncle'), ('niece_nephew', 'Niece/Nephew'), ('cousin', 'Cousin'), ('in_law', 'In-law'), ('guardian', 'Guardian'), ('other', 'Other')], default='other', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.BooleanField(default=False)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('text', 'Text Message')], default='email', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
