# Generated by Django 6.0.3 on 2026-04-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicalrecord',
            new_name='medical_his_patient_da895b_idx',
            old_name='medical_his_patient_idx_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalrecord',
            new_name='medical_his_patient_af7ddb_idx',
            old_name='medical_his_patient_idx2_idx',
        ),
    ]
